version: 0.2

env:
  variables:
      TAGS: "bindata"
     # key: "value"
  #parameter-store:
     # key: "value"
     # key: "value"
  #secrets-manager:
     # key: secret-id:json-key:version-stage:version-id
     # key: secret-id:json-key:version-stage:version-id
  #exported-variables:
     # - variable
     # - variable
  #git-credential-helper: yes
#batch:
  #fast-fail: true
  #build-list:
  #build-matrix:
  #build-graph:
phases:
  #install:
    #If you use the Ubuntu standard image 2.0 or later, you must specify runtime-versions.
    #If you specify runtime-versions and use an image other than Ubuntu standard image 2.0, the build fails.
    #runtime-versions:
      # name: version
      # name: version
    #commands:
      # - command
      # - command
  pre_build:
    commands:
      - echo "----------Pre-build step!----------"
      - id
      - ls -la
      - pwd
#       - make clean-all
  build:
    commands:
       - echo "----------Build step!----------"
       - make build
       - go build contrib/environment-to-ini/environment-to-ini.go
       - echo "----------Run tests!----------"
       - runuser -l codebuild-user -c "make test#TestAdminViewUsers"
  post_build:
    commands:
       - echo "----------Post-Build step!----------"
       - pwd
       - ls -la
       - ls -la /sbin/runuser
       - cat /etc/passwd
         #       - runuser -l codebuild-user -c "make test#TestAdminViewUsers"
#       - make test#TestAdminViewUsers
#reports:
  #report-name-or-arn:
    #files:
      # - location
      # - location
    #base-directory: location
    #discard-paths: yes
    #file-format: JunitXml | CucumberJson
artifacts:
  files:
     - gitea
     - Procfile
     - Buildfile
     - environment-to-ini
     - .ebextensions/01-storage-efs-mountfilesystem.config
     - .ebextensions/05-directories-for-application.config
     - .ebextensions/10-application-configuration-template.config
     - .ebextensions/15-application-configuration-generate.config
  #name: gitea-$(git describe --tags --abbrev=0)-$(date +%Y-%m-%d)
  #discard-paths: yes
  #base-directory: gitea-artifacts
#cache:
  #paths:
    # - paths
