version: 0.2

env:
  variables:
    TAGS: "bindata"
    CGO_ENABLED: "0"
    GOOS: "linux"

phases:
  install:
    commands:
      - echo Starting the Docker daemon...
      - ls -la
      - /usr/local/bin/dockerd-entrypoint.sh
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - export IMAGE_TAG=$(git describe --tags --abbrev=0)
      - export EKS_CLUSTER_NAME=dev-gitea-eks
      - export EKS_KUBECTL_ROLE_ARN="arn:aws:iam::$AWS_ACCOUNT_ID:role/CodeBuildRole"
  build:
    commands:
      - echo Build started on `date`
      - ls -la
      - env
        #- make build
        #- go build contrib/environment-to-ini/environment-to-ini.go
      - echo Tests started on `date`
        #- make test-frontend
      - pwd
      - ls -la
      - id
      - echo Building the Docker image...
        #- docker version
        #- docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
        #- docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
        #- docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:latest
        #- ls -la
        #- pwd
        #- docker images
  post_build:
    commands:
      #- echo Pushing the Docker image...
      #- docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      #- docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:latest
      - echo Deploy to EKS...
      - aws sts get-caller-identity
      #- aws eks --region eu-central-1 update-kubeconfig --name dev-gitea-eks
      - echo "Setting Environment Variables related to AWS CLI for Kube Config Setup"          
      - CREDENTIALS=$(aws sts assume-role --role-arn $EKS_KUBECTL_ROLE_ARN --role-session-name codebuild-kubectl --duration-seconds 900)
      - export AWS_ACCESS_KEY_ID="$(echo ${CREDENTIALS} | jq -r '.Credentials.AccessKeyId')"
      - export AWS_SECRET_ACCESS_KEY="$(echo ${CREDENTIALS} | jq -r '.Credentials.SecretAccessKey')"
      - export AWS_SESSION_TOKEN="$(echo ${CREDENTIALS} | jq -r '.Credentials.SessionToken')"
      - export AWS_EXPIRATION=$(echo ${CREDENTIALS} | jq -r '.Credentials.Expiration')
      - echo "Credentials Value is..  ${CREDENTIALS}"      
      - echo "AWS_ACCESS_KEY_ID...  ${AWS_ACCESS_KEY_ID}"            
      - echo "AWS_SECRET_ACCESS_KEY...  ${AWS_SECRET_ACCESS_KEY}"            
      - echo "AWS_SESSION_TOKEN...  ${AWS_SESSION_TOKEN}"            
      - echo "AWS_EXPIRATION...  $AWS_EXPIRATION"             
      - echo "EKS_CLUSTER_NAME...  $EKS_CLUSTER_NAME"         
      #- echo $AWS_ACCESS_KEY_ID
      #- echo $AWS_SECRET_ACCESS_KEY
      # Setup kubectl with our EKS Cluster              
      - echo "Update Kube Config"      
      - aws eks --region $AWS_DEFAULT_REGION update-kubeconfig --name $EKS_CLUSTER_NAME
      - cat /root/.kube/config
      - aws sts get-caller-identity --query Arn
      - kubectl version --short
      - kubectl cluster-info
      - kubectl get nodes
