---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-sc
  labels:
    pvc: second
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
    - ReadWriteOnce
  storageClassName: efs-sc
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: "fs-0e9fb8918c7936f33::fsap-00e4afaffcd2cfa51"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-claim
  namespace: gitea-testing
  labels:
    app: gitea
    type: efs
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  selector:
    matchLabels:
      pvc: second
  resources:
    requests:
      storage: 5Gi
